set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(3RDPARTY_TCL_DIR "C:/OCCT_3rd_parties/tcltk8617-intel2023" CACHE PATH "")
set(3RDPARTY_TCL_INCLUDE_DIR "C:/OCCT_3rd_parties/tcltk8617-intel2023/include" CACHE PATH "")
set(3RDPARTY_TCL_LIBRARY_DIR "C:/OCCT_3rd_parties/tcltk8617-intel2023/lib" CACHE PATH "")
set(3RDPARTY_TK_INCLUDE_DIR "C:/OCCT_3rd_parties/tcltk8617-intel2023/include" CACHE PATH "")
set(3RDPARTY_TK_LIBRARY_DIR "C:/OCCT_3rd_parties/tcltk8617-intel2023/lib" CACHE PATH "")
set(3RDPARTY_TK_DLL_DIR "C:/OCCT_3rd_parties/tcltk8617-intel2023/bin" CACHE PATH "")
set(3RDPARTY_FREETYPE_DIR "C:/OCCT_3rd_parties/freetype-2.5.5-vc14-64" CACHE PATH "")
set(3RDPARTY_FREETYPE_INCLUDE_DIR_ft2build "C:/OCCT_3rd_parties/freetype-2.5.5-vc14-64/include" CACHE PATH "")
set(3RDPARTY_FREETYPE_INCLUDE_DIR_freetype2 "C:/OCCT_3rd_parties/freetype-2.5.5-vc14-64/include" CACHE PATH "")
set(3RDPARTY_FREETYPE_LIBRARY_DIR "C:/OCCT_3rd_parties/freetype-2.5.5-vc14-64/lib" CACHE PATH "")
set(3RDPARTY_FREETYPE_DLL_DIR "C:/OCCT_3rd_parties/freetype-2.5.5-vc14-64/bin" CACHE PATH "")